namespace Replace.Common.Gateway
{
    public enum ClientOpcode : ushort
    {
        CLIENT_GATEWAY_PATCH_REQUEST = 0x6100,
        CLIENT_GATEWAY_SHARD_LIST_REQUEST = 0x6101,
        CLIENT_GATEWAY_LOGIN_REQUEST = 0x6102,
        CLIENT_GATEWAY_NOTICE_REQUEST = 0x6104,
        CLIENT_GATEWAY_SHARD_LIST_PING_REQUEST = 0x6106,
        CLIENT_GATEWAY_LOGIN_IBUV_ANSWER = 0x6323
    }

    public enum ServerOpcode : ushort
    {
        SERVER_GATEWAY_PATCH_RESPONSE = 0xA100,
        SERVER_GATEWAY_SHARD_LIST_RESPONSE = 0xA101,
        SERVER_GATEWAY_LOGIN_RESPONSE = 0xA102,
        SERVER_GATEWAY_NOTICE_RESPONSE = 0xA104,
        SERVER_GATEWAY_SHARD_LIST_PING_RESPONSE = 0xA106,
        SERVER_GATEWAY_LOGIN_IBUV_RESULT = 0xA323
    }
}
